plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\AI目录\\茜的AI智能客服\\动态简历\\发布包"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]